AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application

Globals:
  Function:
    Timeout: 30

Resources:
  TweetBarrel:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: lambda/.
      Description: Make a tweet on behalf of @mlb_barrels
